idch:
  host: https://api.idcloudhost.com/
  token: ${IDCH_TOKEN} # please populate through environment
  access_name: konfersi-mpi

cluster:
  name: konfersi_cluster
  location: sgp01
  network_uuid: 0af9b107-d1d4-4c3d-84fc-71299e5c5c32
  username: konfersiadmin
  password: ${CLUSTER_NODE_PASSWORD}
  keypair:
    public: keys/id_rsa.pub
    private: keys/id_rsa # used for SSH

master:
  os_name: docker
  os_version: 24.x
  cloud_init:
    files: assets
    runcmd:
      - 0-empty.sh
    environments:
      - "TEST_ENV_MASTER=this env was came from master config"
      - "GDRIVE_ROOT_FOLDER_ID=1-fxBjSiB0q3qYIic2r_dGomP88xgn4Sj"
      - "GDRIVE_CREDENTIAL_FILE=konfersi-service-account-gdrive.json"
  init_resources:
    cpu: 2 # min
    memory: 2 # min
    storage: 150
  resources:
    cpu: 16 # max
    memory: 8 # min
    storage: 200

worker:
  nodes: 5
  os_name: ubuntu
  os_version: 20.04-lts
  cloud_init:
    files: assets
    runcmd:
      - 0-init-server.sh
      - "TEST_ENV_WORKER=this env was came from worker config"
    environments:
  resources:
    cpu: 16 # max
    memory: 8 # max
    storage: 20 # min