idch:
  host: https://api.idcloudhost.com/
  token: ${IDCH_TOKEN} # please populate through environment
  access_name: konfersi-mpi

cluster:
  name: konfersi_cluster
  location: sgp01
  network_uuid: 0af9b107-d1d4-4c3d-84fc-71299e5c5c32
  username: konfersiadmin
  password: ${CLUSTER_NODE_PASSWORD}
  keypair:
    public: keys/id_rsa.pub
    private: keys/id_rsa # used for SSH

master:
  os_name: ubuntu
  os_version: 20.04-lts
  cloud_init:
    files:
      - assets/0-init-server.sh
      - assets/1b-init-runner.yaml
      - assets/2-docker-install.sh
      - assets/3a-docker-swarm-init.sh
      - assets/4-docker-portainer-install.sh
      - assets/4-portainer-agent-stack.yml
      - assets/5-docker-grafana-install.sh
      - assets/5-grafana-agent-stack.yml
      - assets/6-docker-nfs-install.sh
      - assets/8-mpich-init.sh
      - assets/8-mpich-agent-stack.yaml
      - assets/8-mpich-rclone-install.sh
      - assets/transfer.sh
      - assets/konfersi-service-account-gdrive.json
      - transfer-config.yaml
    runcmd:
      - 0-init-server.sh
    environments:
      - "GDRIVE_ROOT_FOLDER_ID=1-fxBjSiB0q3qYIic2r_dGomP88xgn4Sj"
      - "GDRIVE_CREDENTIAL_FILE=konfersi-service-account-gdrive.json"
      - "PORTAINER_ADMIN_PASSWORD=konfersiindonesia"
      - "GRAFANA_USERNAME=konfersiadmin"
      - "GRAFANA_PASSWORD=konfersiindonesia"
      - "MPICH_BASE_IMAGE=alfianisnan26/konfersi-mpi:latest"
      - "MPICH_PASSWORD=konfersiindonesia"
      - "MPICH_WORKER_REPLICAS=5"
      - "MPICH_WORKER_CPU_LIMIT=15"
      - "MPICH_WORKER_MEMORY_LIMIT=2500"
  
  resources:
    cpu: 16 # max
    memory: 8 # min
    storage: 200
    init:
      cpu: 2 # min
      memory: 2 # min
      storage: 150
    

worker:
  nodes: 5
  os_name: ubuntu
  os_version: 20.04-lts
  cloud_init:
    files:
      - assets/0-init-server.sh
      - assets/1b-init-runner.yaml
      - assets/2-docker-install.sh
      - assets/3b-docker-swarm-join.sh
      - assets/0-empty.sh
    runcmd:
      - 0-init-server.sh
    environments:
  resources:
    cpu: 2 # max
    memory: 2 # max
    storage: 20 # min