version: '3'

services:
  mpi_master:
    image: ${MPICH_BASE_IMAGE}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "8822:3000"
    volumes:
      - mpi.vol:/home/mpi/workspace
    networks:
      - mpi-cluster
    environment:
      - ROLE=master
      - PASSWORD=${MPICH_PASSWORD}
      - MASTER_HOSTNAME=mpi_master
      - WORKER_HOSTNAME=mpi_worker

  mpi_worker:
    image: ${MPICH_BASE_IMAGE}
    deploy:
      mode: global
      resources:
        limits:
            cpus: '${MPICH_WORKER_CPU_LIMIT}'
            memory: '${MPICH_WORKER_MEMORY_LIMIT}M'
      placement:
        constraints:
          - node.role == worker
    volumes:
      - mpi.vol:/home/mpi/workspace
    networks:
      - mpi-cluster
    environment:
      - ROLE=worker
      - MASTER_HOSTNAME=mpi_master
      - WORKER_HOSTNAME=mpi_worker

volumes:
  mpi.vol:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${MASTER_NODE_IP},nfsvers=4.1,rw,hard,nolock"
      device: ":"

networks:
  mpi-cluster:
    driver: overlay                    # Use the overlay network driver for Swarm
    ipam:
      driver: default                   # Use the default IPAM driver
      config:
        - subnet: 10.26.0.0/16          # Define subnet with CIDR notation (make sure to include the netmask, e.g., /24)
