version: '3'

services:
  mpi_master:
    image: alfianisnan26/konfersi-mpi:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "8822:3000"
    volumes:
      - mpi.vol:/home/mpi/workspace
    networks:
      - mpi-cluster
    environment:
      - ROLE=master
      - PASSWORD=konfersiindonesia
      - MASTER_HOSTNAME=mpi_master
      - WORKER_HOSTNAME=mpi_worker

  mpi_worker:
    image: alfianisnan26/konfersi-mpi:latest
    deploy:
      replicas: 1
      resources:
        limits:
            cpus: '15'
            memory: 2500M
    volumes:
      - mpi.vol:/home/mpi/workspace
    networks:
      - mpi-cluster
    environment:
      - ROLE=worker
      - PASSWORD=konfersiindonesia
      - MASTER_HOSTNAME=mpi_master
      - WORKER_HOSTNAME=mpi_worker

volumes:
  mpi.vol:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${MASTER_NODE_IP},nfsvers=4.1,rw,hard,nolock"
      device: ":/mpich"

networks:
  mpi-cluster:
    driver: overlay                    # Use the overlay network driver for Swarm
    ipam:
      driver: default                   # Use the default IPAM driver
      config:
        - subnet: 10.0.26.0/24          # Define subnet with CIDR notation (make sure to include the netmask, e.g., /24)
